imports:
    - { resource: services/ }

parameters:
    app_title: "%env(APP_TITLE)%"
    avatar_directory: '%kernel.project_dir%/public/uploads/user/avatar'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\User\AvatarUploader:
        arguments:
            $targetDirectory: '%avatar_directory%'

