imports:
    - { resource: services/ }

parameters:
    app_title: "%env(APP_TITLE)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

