imports:
    - { resource: services/ }

parameters:
    app_title: "%env(APP_TITLE)%"
    avatar_directory: '%kernel.project_dir%/public/uploads/user/avatar'
    attachment_directory: '%kernel.project_dir%/var/uploads/attachments'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\User\AvatarUploader:
        arguments:
            $targetDirectory: '%avatar_directory%'

    App\Service\Ticket\AttachmentUploader:
        arguments:
            $targetDirectory: '%attachment_directory%'

    App\Service\Notification\Notifier\:
        resource: '../src/Service/Notification/Notifier/*'
        tags: [ app.ticket_event_notifier ]

    App\Service\Notification\Channel\:
        resource: '../src/Service/Notification/Channel/*'
        tags: [ app.ticket_event_channel ]

    App\Service\Notification\NotificationManager:
        bind:
            $notifiers: !tagged_iterator app.ticket_event_notifier
            $channels: !tagged_iterator app.ticket_event_channel

