imports:
    - { resource: services/ }

parameters:
    app_title: "%env(APP_TITLE)%"
    avatar_directory: '%kernel.project_dir%/public/uploads/user/avatar'
    attachment_directory: '%kernel.project_dir%/var/uploads/attachments'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\User\AvatarUploader:
        arguments:
            $targetDirectory: '%avatar_directory%'

    App\Service\Ticket\AttachmentUploader:
        arguments:
            $targetDirectory: '%attachment_directory%'

