version: "3.5"
services:
    mercure:
        image: dunglas/mercure:latest
        restart: unless-stopped
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_JWT_SECRET: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://localhost:3000 http://127.0.0.1:8000 https://${WARDEN_ENV_NAME}.test
                demo
        volumes:
            - mercure_data:/data
            - mercure_config:/config
        labels:
            - traefik.enable=true
            - traefik.http.routers.${WARDEN_ENV_NAME}-mercure.rule=Host(`mercure.${WARDEN_ENV_NAME}.test`)
            - traefik.http.routers.${WARDEN_ENV_NAME}-mercure.tls=true
            - traefik.http.services.${WARDEN_ENV_NAME}-mercure.loadbalancer.server.port=80

volumes:
    mercure_data:
    mercure_config:
